[dev]
	command = "yarn dev:server" # Command to start your dev server
	port = 7999 # Port that the dev server will be listening on
	publish = "public" # If you use a _redirect file, provide the path to your static content folder’
    targetPort = 7998
    framework="#custom"